### ISSUE TITLE
Add Tests and Travis CI

### ISSUE THREAD

**Issue by peter279k** [katmore/micro-encode#1]
As title, can I use the PHPUnit to add the unit test and integrate the Travis CI service?

Thanks.

**Comment by ackspony** [comment]
sure, feel free to do a PR or let me know any questions you have before proceeding

**Comment by ackspony** [comment]
closing this issue as I have created some initial unit tests as of release [v1.0.3](https://github.com/katmore/micro-encode/tree/v1.0.3)
